---
title: "Project"
author: "Melis K Topcu"
subtitle: "Investigation into Chicago taxis"
echo: false
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---

## Packages

We will use the **tidyverse, tidymodels** and **scales** packages for data wrangling and visualization.

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(tidymodels)
library(scales)
```

## Data

The dataset we will explore is called `taxi`. Let's `glimpse()` at it.

```{r}
#| label: glimpse-taxi
glimpse(taxi)
```

## Question 1

Is there there a relationship between the distance (in miles) someone travels in a taxi and if they tip or not?

```{r}
#| label: relationship-between-distance-and-tip
ggplot(taxi, aes (x = distance, y = tip, fill = tip)) +
         geom_boxplot(show.legend = FALSE) +
  labs(
    x = "Distance (miles)",
    y = "Tip",
    title = "Relationship between distance and tip"
  )

```

More tips are given if the trip is longer.

## Question 2

## Your own question
